# Use Python 3.11
FROM python:3.11-slim-bookworm

# Install dependencies
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2 \
      && apt update \
      && apt install -y \
            software-properties-common \
            ant \
            g++-11 \
            zlib1g-dev \
            libcurl4-openssl-dev \
            zlib1g-dev \
            libfftw3-dev \
            libc++-dev \
            hdf5-tools \
            tk \
            python3-launchpadlib \
            python3-tk \
            build-essential \
            procps \
            less \
            htop \
            vim \
            nano \
            tmux \
            git \
            rsync \
            wget \
      && add-apt-repository ppa:openjdk-r/ppa \
      && apt update \
      && apt install -y \
            default-jre \
            default-jdk

# Install TF-COMB & Jupyter Notebook
RUN pip3 install TF-COMB && \
    pip3 --no-cache-dir install jupyterlab && \
    pip3 --no-cache-dir install notebook
