# See: https://github.com/Washington-University/HCPpipelines/wiki/Installation-and-Usage-Instructions

# Prerequisite 1: Ubuntu 22.04
FROM ubuntu:22.04

# Install dependencies
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2 \
      && apt update \
      && apt install -y \
            curl \
            software-properties-common \
            ant \
            g++-11 \
            zlib1g-dev \
            libcurl4-openssl-dev \
            zlib1g-dev \
            libfftw3-dev \
            libc++-dev \
            hdf5-tools \
            python3-launchpadlib \
            build-essential \
            libeigen3-dev \
            qtbase5-dev \
            libqt5svg5* \
            cmake \
            procps \
            less \
            htop \
            vim \
            nano \
            tmux \
            git \
            rsync \
            wget \
            python3-numpy \
            python3-pip \
            python3-venv \
            unzip \
      && add-apt-repository ppa:openjdk-r/ppa \
      && apt update \
      && apt install -y \
            default-jre \
            default-jdk

# Prerequisite 7: Python3 environment (TESTED - VERIFIED)
ENV VIRT_ENV=/opt/venv
RUN python3 -m venv $VIRT_ENV
ENV PATH=$VIRT_ENV/bin:$PATH
RUN pip3 install --upgrade pip numpy nibabel

# Prerequisite 2: FMRIP Software Library (TESTED - VERIFIED)
RUN wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/releases/getfsl.sh -O fsl.sh && sh fsl.sh && rm fsl.sh
ENV FSLDIR=/root/fsl/bin
ENV PATH=$FSLDIR:$PATH

# Prerequisite 3: freesurfer (UNTESTED)
RUN mkdir -p /usr/local/freesurfer
RUN wget https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz
RUN tar -xzf freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz -C /usr/local/freesurfer && rm freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz
RUN export PATH=/usr/local/freesurfer:$PATH
RUN export FS_LICENSE=/usr/local/freesurfer/license.txt # TODO: Add license file to RIS

# Prerequisite 4: Connectome Workbench (TESTED - VERIFIED)
RUN mkdir -p /usr/local/connectome-workbench
RUN wget https://www.humanconnectome.org/storage/app/media/workbench/workbench-linux64-v2.1.0.zip
RUN unzip workbench-linux64-v2.1.0.zip -d /usr/local/connectome-workbench && rm workbench-linux64-v2.1.0.zip
RUN chmod +x /usr/local/connectome-workbench/workbench/bin_linux64
ENV C3W_HOME=/usr/local/connectome-workbench/workbench/bin_linux64
ENV PATH=$C3W_HOME:$PATH

# Prerequisite 5: gradunwarp (TESTED - VERIFIED)
RUN pip3 install git+https://github.com/Washington-University/gradunwarp.git@1.2.3

# Prerequisite 6: MSM_HOCR v3.0 (TESTED - VERIFIED)
RUN mkdir -p /usr/local/msm_hocr
RUN wget https://github.com/ecr05/MSM_HOCR/releases/download/v3.0FSL/msm_centos_v3 && mv msm_centos_v3 /usr/local/msm_hocr/msm_hocr
RUN chmod +x /usr/local/msm_hocr/msm_hocr
ENV MSM_HOCR_HOME=/usr/local/msm_hocr
ENV PATH=$MSM_HOCR_HOME:$PATH

# Prerequisite 8: MRTrix3 (TESTED - VERIFIED)
https://mrtrix.readthedocs.io/en/latest/installation/deployment.html
RUN git clone http://github.com/MRtrix3/mrtrix3.git
RUN cd mrtrix3 && ./configure
RUN cd mrtrix3 && ./build
RUN cd mrtrix3 && tar cvfz mrtrix3.tgz bin/ lib/ share/
RUN mkdir /usr/local/mrtrix3
RUN cd mrtrix3 && cp ./mrtrix3.tgz /usr/local/mrtrix3/
RUN cd /usr/local/mrtrix3/ && tar xvfz mrtrix3.tgz
ENV PATH=/usr/local/mrtrix3/bin:$PATH

# Prerequisite 9: ANTs (Advanced Normalization Tools)

# Prerequisite 10: c3d_affine_tool

