# See: https://github.com/Washington-University/HCPpipelines/wiki/Installation-and-Usage-Instructions

# Prerequisite 1: Ubuntu latest LTS
FROM ubuntu:latest

# Install dependencies
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2 \
      && apt update \
      && apt install -y \
            curl \
            software-properties-common \
            ant \
            g++-11 \
            zlib1g-dev \
            libcurl4-openssl-dev \
            zlib1g-dev \
            libfftw3-dev \
            libc++-dev \
            hdf5-tools \
            python3-launchpadlib \
            build-essential \
            libeigen3-dev \
            qtbase5-dev \
            libqt5svg5* \
            cmake \
            procps \
            less \
            htop \
            vim \
            nano \
            tmux \
            git \
            rsync \
            wget \
            file \
            dc \
            mesa-utils \
            pulseaudio \
            libquadmath0 \
            libopenblas-dev \
            libgtk2.0-0 \
            firefox \
            libgomp1 \
            python3-numpy \
            python3-pip \
            python3-venv \
            unzip

# Prerequisite 7: Python3 environment
ENV VIRT_ENV=/opt/venv
RUN python3 -m venv $VIRT_ENV
ENV PATH=$VIRT_ENV/bin:$PATH
RUN pip3 install --upgrade pip numpy nibabel

# Prerequisite 2: FMRIP Software Library
ENV FSLDIR=/usr/local/fsl
ENV PATH=$FSLDIR/bin:$PATH
RUN wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/releases/fslinstaller.py
RUN python ./fslinstaller.py -d /usr/local/fsl/

# Prerequisite 3: freesurfer
RUN mkdir -p /usr/local/freesurfer
RUN wget https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz \
      && tar -xzf freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz \
      && mv freesurfer /usr/local/ \
      && rm freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz
COPY license.txt /usr/local/freesurfer/license.txt
ENV PATH=/usr/local/freesurfer/bin:$PATH
ENV FS_LICENSE=/usr/local/freesurfer/license.txt

# Prerequisite 4: Connectome Workbench
RUN mkdir -p /usr/local/connectome-workbench
RUN wget https://www.humanconnectome.org/storage/app/media/workbench/workbench-linux64-v2.1.0.zip \
      && unzip workbench-linux64-v2.1.0.zip -d /usr/local/connectome-workbench \
      && rm workbench-linux64-v2.1.0.zip \
      && chmod +x /usr/local/connectome-workbench/workbench/bin_linux64
ENV C3W_HOME=/usr/local/connectome-workbench/workbench/bin_linux64
ENV PATH=$C3W_HOME:$PATH

# Prerequisite 5: gradunwarp
RUN pip3 install git+https://github.com/Washington-University/gradunwarp.git@1.2.3

# Prerequisite 6: MSM_HOCR v3.0
RUN mkdir -p /usr/local/msm_hocr
RUN wget https://github.com/ecr05/MSM_HOCR/releases/download/v3.0FSL/msm_centos_v3 \
      && mv msm_centos_v3 /usr/local/msm_hocr/msm_hocr \
      && chmod +x /usr/local/msm_hocr/msm_hocr
ENV MSM_HOCR_HOME=/usr/local/msm_hocr
ENV PATH=$MSM_HOCR_HOME:$PATH

# Prerequisite 8: MRTrix3
RUN mkdir -p /usr/local/mrtrix3
RUN git clone http://github.com/MRtrix3/mrtrix3.git \
      && cd mrtrix3 \
      && ./configure \
      && ./build \
      && tar cvfz mrtrix3.tgz bin/ lib/ share/ \
      && mv mrtrix3.tgz /usr/local/mrtrix3/ \
      && cd /usr/local/mrtrix3/ \
      && tar xvfz mrtrix3.tgz \
      && rm mrtrix3.tgz
ENV PATH=/usr/local/mrtrix3/bin:$PATH

# Prerequisite 9: ANTs
RUN wget https://github.com/ANTsX/ANTs/releases/download/v2.6.3/ants-2.6.3-ubuntu-22.04-X64-gcc.zip \
      && unzip ants-2.6.3-ubuntu-22.04-X64-gcc.zip \
      && mv ants-2.6.3 /usr/local/ants \
      && rm ants-2.6.3-ubuntu-22.04-X64-gcc.zip
ENV ANTS_HOME=/usr/local/ants
ENV PATH=$ANTS_HOME/bin:$PATH

# Prerequisite 10: c3d
RUN wget https://sourceforge.net/projects/c3d/files/c3d/Nightly/c3d-nightly-Linux-gcc64.tar.gz/download -O c3d-nightly-Linux-gcc64.tar.gz \
      && tar -xzf c3d-nightly-Linux-gcc64.tar.gz \
      && mv c3d-1.4.4-Linux-gcc64 /usr/local/c3d \
      && rm c3d-nightly-Linux-gcc64.tar.gz
ENV C3D_HOME=/usr/local/c3d
ENV PATH=$C3D_HOME/bin:$PATH
